from django.db import models
from django.contrib.auth.models import AbstractUser
from ph_geography.models import Municipality, Barangay

class Account(AbstractUser):
    last_name = models.CharField(max_length=255, blank=True, null=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    maiden_name = models.CharField(max_length=255, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    membership_category = models.CharField(max_length=255, blank=True, null=True)
    is_bh_member = models.BooleanField(blank=True, null=True)
    region = models.CharField(max_length=255, blank=True, null=True)
    province = models.CharField(max_length=255, blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    city_municipality = models.ForeignKey(Municipality, on_delete = models.CASCADE, blank=True, null=True)
    barangay = models.ForeignKey(Barangay, on_delete = models.CASCADE, blank=True, null=True)
    street = models.CharField(max_length=255, blank=True, null=True)
    house_no = models.CharField(max_length=255, blank=True, null=True)
    e_wallet_account = models.CharField(max_length=255, blank=True, null=True)
    e_wallet_account_name = models.CharField(max_length=255, blank=True, null=True)
    e_wallet_account_number = models.CharField(max_length=255, blank=True, null=True)
    precinct_number = models.CharField(max_length=255, blank=True, null=True)
    family_voters_count = models.IntegerField(blank=True, null=True)
    fb_messenger_account = models.CharField(max_length=255, blank=True, null=True)
    contact_number = models.CharField(max_length=255, blank=True, null=True)
    photo = models.ImageField(upload_to='UserModule/static/photos/', blank=True, null=True)
    signature = models.ImageField(upload_to='UserModule/static/signatures/', blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    bh_social_services = models.CharField(max_length=255, default='None', blank=True, null=True)
    project_in_my_area = models.CharField(max_length=255, default='None', blank=True, null=True)
    bh_id = models.CharField(max_length=255, default='None', blank=True, null=True )
    qr_code = models.ImageField(upload_to='UserModule/static/qr_code/', blank = True, null = True)
    isVerified = models.BooleanField(default=False)
