# Generated by Django 3.2.6 on 2024-05-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bh_id',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='UserModule/static/qr_code/'),
        ),
    ]
