# Generated by Django 3.2.6 on 2024-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_auto_20240604_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.FloatField(blank=True, default=14.6488, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.FloatField(blank=True, default=121.0509, null=True),
        ),
    ]
