# Generated by Django 3.2.6 on 2024-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_auto_20240503_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
