# Generated by Django 3.2.6 on 2024-05-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_account_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='BagongHenerasyon/UserModule/static/photos/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='BagongHenerasyon/UserModule/static/qr_code/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='BagongHenerasyon/UserModule/static/signatures/'),
        ),
    ]
