# Generated by Django 3.2.6 on 2024-05-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0004_auto_20240505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
