# Generated by Django 3.2.6 on 2024-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0005_auto_20240505_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='UserModule/static/photos/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='UserModule/static/qr_code/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='UserModule/static/signatures/'),
        ),
    ]
